version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./back:/var/www
      - ./docker/nginx/default-dev.conf:/etc/nginx/conf.d/default-dev.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php-fpm
      - react-app
    networks:
      - app-network
  php-fpm:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    volumes:
      - ./back:/var/www
      - /var/www/vendor
      - ./back/php-fpm/logs:/var/log/php-fpm
    depends_on:
      - mysql
    networks:
      - app-network
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3366:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - app-network
  react-app:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front:/app
      - /app/node_modules
    networks:
      - app-network
  test-prod-mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${TEST_PROD_MYSQL_DATABASE}
      MYSQL_USER: ${TEST_PROD_MYSQL_USER}
      MYSQL_PASSWORD: ${TEST_PROD_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TEST_PROD_MYSQL_ROOT_PASSWORD}
    ports:
      - "3399:3306"
    volumes:
      - test-prod-mysql:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    # Не используем общую сеть
volumes:
  mysqldata:
  test-prod-mysql:

networks:
  app-network:
    driver: bridge